language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
notifications:
  email:
    recipients:
    - sami@nieminen.fi
    on_success: change
    on_failure: always
    

deploy:
  provider: heroku
  api_key:
    secure: IN+d3n5hcYlLeaP9FSN6JCbEDDh6lbLrLh4E+U5V4v1ah9FLRv/Pltrz0zuxFPQSamYBd6/q2J7eyYpKdJQQJ1md9Qag4KLxIgibLKPUnw8iwRRD4X28+Hf6y65K/5Fczek6QPTFec3mubsmhm3SUJGr1cHjAiVcUbBDvzDMabxUKCGml34/ptUf3TFa0YVd9fTbxYUh7Yy7EFBhZcijTVGyWw/0qv9XK9V+UUECjvIfIvKgB1OywtCaTCpW2Ww/RX9SYYanjDc25kl/XQ7+kg5RtG3/IWTlqZOtvYr1DR+paPk4tJL3V8I0NdjpTbK/s+2SL/9IRXyJGf1KUUmbos7tRoeNfsknogYMducgGBiviGY94xt2Bg5R3cfpdC1C3xnh2V4e3grxuPpyKfmlVbVFLXJRTybUsEwLg1sTZsC6Hjg4sdJPk8QDMkCqTIq/zUP31usYY9HRLSmR7x/tJhYYcRC3ZuQEX62dgLaQVZfj9od7tjBaQAmU0ZYfFH+hP1ynIG5EUhiO7ZbGUypnLMWjE4ASs0waoniQxo4RhRpYwyWdjJxxIlPmI0KzrpBPND8jR8/0DHVbJBsG3fZZfJZYCZjEAHq6VwNuNLXbr34d9P1a0cJ9KN6YsiTU+hUjVXXzCT/PGMGi0HmOpUz1AbdXYa5Ti161bg2pz5BE0+k=
  app: full-stack-blog-app
  on:
    repo: niemisami/full-stack-open-blog
